insert into time(end_time, start_time) values ( '9:00:00','10:00:00' );
insert into time(end_time, start_time) values ( '10:00:00','11:00:00' );
insert into time(end_time, start_time) values ( '11:00:00','12:00:00' );
insert into time(end_time, start_time) values ( '12:00:00','13:00:00' );
insert into time(end_time, start_time) values ( '13:00:00','14:00:00' );
insert into restaurant (city, state, street, zip_code, name) values ('Fairfiled','IA','1000 NT 4th street',52557,'Anapurna');
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into dining_table(capacity) values ( 4 );
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,1);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,2);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,3);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,4);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,5);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,6);
insert into restaurant_dining_tables(restaurant_id, dining_tables_id) values (1,7);